### ISSUE TITLE
Сортировка списка не просмотренных сериалов

### ISSUE THREAD

**Issue by RJ2k6** [flytaly/myshows-tracker#1]
Доброго.
Обнаружил проблему с сортировкой списка не просмотренных сериалов в разделе "Сериалы". Сортировка всегда в алфавитном порядке, независимо от выбора параметра в настройке "Порядок вывода эпизодов и сезонов". Причем сортировка идет по оригинальному названию, а не по локализированному. В подобном расширении для Хрома сортировка идет по времени выхода нового эпизода в сериале. Сверху новые, снизу старые. И они сверху постепенно добавляются по мере выхода. Так удобно смотреть.

**Comment by flytaly** [comment]
Наконец-то дошли руки обновить расширение. Теперь в [v1.2.0](https://addons.mozilla.org/ru/firefox/addon/myshows-tv-show-tracker/versions/) сериалы по-умолчанию сортируются по новым эпизодам
