### ISSUE TITLE
[Feature request] Opiton to use english version of site

### ISSUE THREAD

**Issue by Artnel** [flytaly/myshows-tracker#6]
When I select any link in extension popup it sends me to Russian version of site. Please add option to use another languages.

**Comment by flytaly** [comment]
Yeah, for some reason website doesn't redirect you when you are logged in. 
I added an option to open the English version in [1.2.2 version:](https://addons.mozilla.org/en-US/firefox/addon/myshows-tv-show-tracker/versions/)

![Screenshot 2020-04-17 at 01 42 23](https://user-images.githubusercontent.com/1577569/79513505-b160c380-804c-11ea-995e-1e97545cff9a.png)
