### ISSUE TITLE
Проблемка с "Календарь: эпизоды одного сериала выходящие одновременно сгруппированы в одну строчку"

### ISSUE THREAD

**Issue by RJ2k6** [flytaly/myshows-tracker#7]
Здравствуйте.
Сразу по горячим следам после указанного в названии обновления. Так вот. Обнаружилась ошибка. По какой-то непонятной причине в одну строку сгруппировались эпизоды из разных сериалов. Например, вот: https://i112.fastpic.ru/big/2020/0621/ad/d0adb6f617d68f62c940dce21da7e2ad.png
Эпизод s01e07 из другого сериала под названием "Hightown", но почему-то попавшем в сериал "Black Monday". Кроме того, тоже самое с этими сериалами повторяется и в дальнейшем: https://i112.fastpic.ru/big/2020/0621/a8/2ebd31cd97eb7c499b18a731a5801fa8.png
Сначала думал, что проблема в том, что они вышли в один и тот же день. Но с другими сериалами, которые тоже вышли в один и тот же день проблем нет.
Вот такая непонятная проблемка.

**Comment by flytaly** [comment]
Скорее всего, я банально забыл добавить проверку, что это действительно один и тот же сериал при группировке. 🤦‍♂️ 

К слову, сейчас группируются не "выходящий в один день", а выходяшие в одно и то же время. Так уж, видимо, совпало, что два сериала вышли одновременно.

Сегодня вечером исправлю.
