### ISSUE TITLE
Сбрасываются настройки в 80-х версиях Firefox

### ISSUE THREAD

**Issue by RJ2k6** [flytaly/myshows-tracker#9]
Установил свои настройки. Но через некоторое время замечаешь, что настройки сбросились. После этого иногда настройки можно установить заново, но иногда настройки никак не получается установить.

**Comment by flytaly** [comment]
Проблема все еще присутствует? К сожалению, не могу воспроизвести у себя. Браузер один или несколько? (например, на разных устройствах).

Вообще говоря, настройки хранятся в [синхронизируемом хранилище](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync) и я нашел только одно изменение  в 79 версии FF: они ограничили размер этого хранилища. Но лимитов все равно должно хватать. 

Если настройки все еще сбрасываются, то я могу изменить синхронизируемое хранилище на локальное.

**Comment by RJ2k6** [comment]
Да, проблема осталась. Это началось с перехода на 80-ю версию. Вот для наглядности:
https://i112.fastpic.ru/big/2020/0912/5d/cf3582fae1e5c6728c7f517d52569b5d.png
В окне справа у меня всегда идет сначала оригинальное название сверху и на русском снизу. В поиске две ссылки. Теперь это всё сбросилось. В настройках, как видно, пытаюсь нажать на меньший шрифт, а он не нажимается. Пытаюсь добавить поиск, не добавляется. Галки поставить можно и выбрать там порядок названия, выбираешь, а они не срабатывают. Единственное решение - снести и переустановить. После переустановки через некоторое время снова все настройки слетают.

**Comment by flytaly** [comment]
Ясно, понял где ошибка в коде есть. Если ты проделаешь [действия как на видео](https://imgur.com/a/yuzyOOq), то там наверняка в консоле будет ошибка. Что-то вроде `SyntaxError: JSON.parse`. 
Текст `browser.storage.sync.get().then(console.log)` вводить не обязательно.

Сегодня вечером исправлю.

**Comment by RJ2k6** [comment]
Попробовал, но дело застопорилось вот на этом моменте:
https://i112.fastpic.ru/big/2020/0912/4f/d7e41097a48cf020a6b5734ba6aa364f.png
И как видно, там справа сверху отсутствует кнопка переключение background/options.

**Comment by flytaly** [comment]
Нужно открыть страницу опций (настроек расширения) отдельной вкладкой.

**Comment by RJ2k6** [comment]
Меня тут отвлекли. В общем, сделал еще раз один в один, как на видео, дошел до консоли, но когда я пытаюсь во вкладке настроек что-то поменять (шрифт как в видео), то в этой консоли ничего не отображается. И только минуты три спустя появляются вот такие надписи:
https://i112.fastpic.ru/big/2020/0912/4e/feea9f8195a4354014833a641c163f4e.png

**Comment by flytaly** [comment]
Версия 2.2.2 должна теперь работать нормально.
